module.exports = function getRandomQuote () {
  let i = Math.floor(Math.random() * Math.floor(quotes.length))
  return quotes[i]
}

var quotes = [
  "Oh, and the this is Joe. Don't scare him. He'd probably wet his pants.",
  "Hey, don't worry. We'll find him.",
  "Get 'em, Greymon!",
  'Hey, back off!',
  "How dare you say that, Matt! We're all friends here!",
  'T.K.!',
  "That's Princess Meanie!",
  'Kari? Kari!',
  "Hey, I'm home.",
  "You've picked on the wrong Guy's little sister, Mr. Fang-Face.",
  'WHAMON!!!',
  'My Digi-Vice is going off again.',
  'After him, guys!',
  "I'm taking this kid back!",
  "He's staying with us!",
  'Your opponent is... Greymon!',
  "Oh, I'm so scared! Get him, Greymon!",
  'A man must first face himself before he faces his enemies.',
  'Never trust anything without feet!',
  'Who are you calling a jerk, jerk?',
  "Sure, let's go for a hike. Then after that we'll hike. And then we can hike some more.",
  'Matt must be around here somewhere. Matt!',
  'Or, we could stand here frozen until the monster gets us!',
  'Sora!',
  "I have a foolproof plan: first we'll eat something, then after that... I'm open to suggestions!",
  "I'm glad we never hear you complaining...",
  'Matt! Can you hear me, Matt?',
  "Matt, I'm here!",
  'That could have been a snake, or worse,',
  'Matt! Are you out there?',
  'When we get back, this is gonna make one great story. Yup... but... of course, not a single soul will ever believe me.',
  'Yup, this is him. He happened to see you fall on this island and he got us here in no time.',
  'When we had to survive on our own, we grew up very fast... except for Joe, he just threw up very fast...',
  'But my dad likes his mess where it is...',
  'Matt!',
  "You can do it, and even if you can't, we won't think any less of you, man!",
  "Yeah. That's real inconspicuous.",
  "I thought we'd never find you guys! It is sure lucky we met up with Frigimon.",
  'Maybe we should tell someone important like the principal or Bill Gates or something...',
  'That is the last time I eat camp food!',
  'Matt! Gabumon!',
  'Oh, yeah? Try it, you tincan!',
  'Well, come on!',
  'Great! Anybody bring a helicopter?',
  "We've sacrificed too much to give up now!",
  'Has anybody noticed? We talk a lot about food.',
  "Boy, that's productive. This thing puts the pieces together, and then it takes them apart.",
  "I finally got it figured out. If I'm ever gonna change, I have to do it on my own. On my own. The others can't help me.",
  'If she wants to cry, let her.',
  'Be quiet, T.K.!',
  "I've never let anyone get close to me before.",
  'No question, man, you are the dude of doodles!',
  'Just be quiet and come with me!',
  "You're a thief, we worked to pay for a trip to Hawaii!",
  'Put your fists down when you talk to me and stop acting like you can bully your way into being the leader!',
  'Moving right along, folks... keep it moving... Our next stop on the tour will be the forest of irrelevant road signs. No pictures, please.',
  'Computer guys can never just tell you something. They have to spend all day explaining it to you...',
  'I swore I would never let anyone see me cry. But really, all I ever wanted to do was cry. I hate being alone...',
  'Guys, the closest thing our grandmother has to computer is an egg timer...',
  "They're not weird, they're my best friends! [Quietly] Considering this is the only computer in town...",
  "I'm sick of all your blabbering Davis, you're the only one who hasn't tried yet, so just get in the hole!",
  "First I'll take a little stroll over to our old refrigerator and take a peek at what's not expired...",
  'Is that a ring in your nose or is that an allergic reaction?',
  'Garururmon!',
  'Stop that!',
  "Did it all of a sudden get sunnier - or is it just Tai's sunny disposition?",
  "Remember, it's an amusement park - so like ... amuse yourselves.",
  "It's a secret but I'll tell you... A little bit of hot sauce, a little wasabi and a mystery meat I found in the freezer covered in green fuzz!",
  'Oh, man...after I accused him and yelled at him...he still risked himself for T.K.',
  'T.K.!',
  'WereGarurumon!',
  'Hang on, pal!',
  'You okay?',
  'That was close!',
  'Atta boy.',
  'Wh-what the...?',
  'The black gears!',
  'This is bad! Run, Garurumon!',
  "No! Turn back, or he'll beat you to a pulp!",
  'MetalGarurumon!',
  "Well, at least my cat's not stuck in a tree!",
  "We all know you're tight Tai but just give us a little space!",
  "(Gasps) Wow! Why didn't I pack my fluffy pink snow boots?",
  'Togemon!',
  "I'm gonna sit here and stare at the flowers until everyone starts getting along.",
  'Lillymon!',
  'HELP! Somebody please find us!',
  "We're going to be okay, just keep moving along.",
  'Here, you wear my hat for a while. You need it more than I do,',
  'This beach would be a lot more popular if it had a lot more things, like an ocean, a gentle breeze, a snack bar, a hunky lifeguard, you know?',
  "Maybe they'll have hats for sale, half-off.",
  'Whoops, we went and spent it all.',
  "Now remember T.K., don't move!",
  'Prodigious!',
  'Do you have Internet access?',
  "You're going to need a password! You can use mine to get on the Internet: 'Prodigious'!",
  'Potato chips, chocolate chips... anything but computer chips!',
  'I love you.',
  "I'm one step ahead of you, Tai.",
  "It's Alive!",
  'She appears to be conversing with herself.',
  "Too bad your brain isn't as big as your hair.",
  "Oh, like that's gonna help.",
  'Now that you boys have holes in your heads, maybe your brains will get more oxygen.',
  "I don't care what you're faster than! As long as you're faster than a gigantic, rolling teddy bear!",
  "I'm gonna build the biggest snowman!",
  "Help me! I can't swim so good, Patamon!",
  'Matt, help!',
  'Oh, no!',
  'Patamon, help!',
  'Oh, no! Poor Patamon!',
  'Hiya, Matt!',
  "I thought I'd never see you again,",
  'Matt!',
  "Hey! Let's play a game with the baby Digimon!",
  "What's wrong? [Do you need to/did you] poop?",
  "Okay, so you don't want to play a game!",
  'My parents are still mad at me, for the time I painted our kitty cat.',
  "I don't want to fight, ever!",
  'What do we do, Patamon?',
  'What was that?',
  'Joe?',
  'Patamon, we gotta save him!',
  'Joe? Joe?',
  'Matt, brother...I need you...',
  'Big brother!',
  'You came in time!',
  'I wanna take him home with me,',
  'Be careful!',
  'Angemon!',
  'Matt! Somebody, get me down!',
  "Joe! He's caught!",
  'Matt, help me!',
  "Matt, I'm gonna tell Mom that you were fighting!",
  "Big Bro...you're the best!",
  'Gomamon, get a grip! The last thing we need is any more fighting around here!',
  'Tentomon digivolve to - Kabu never mind...',
  'Very persiptive of you.',
  'How nice, your little brother decided to hang around,',
  'Call off your beast!',
  "Hey! Back off, furball, or the kid's lunchmeat! Got it?",
  'Look out!',
  "I don't know, Kari. I hope so,",
  'You gotta believe me, Matt.',
  "Attack, I'm fine.",
  'Have we seen a bad Digimon? No!',
  'Would you please stop taunting the deranged android?',
  "Tai, I'm so glad to see you, but don't break anything.",
  "Oh, uh...Matt's around back.",
  "That's going too far! I've had it.",
  'Then our friends must be nearby. It did the same thing we found T.K.',
  'Tai, stop that!',
  'Matt, Tai, quit it!',
  'Pepper breath!',
  "Bug up the nose? That's a bad thing?",
  "Agumon digivolve to - Greymon! Greymon! Greymon, yeah, I'm Greymon! I'm big and I'm bad...",
  'T.K.',
  'Gabumon and Matt! Boy, is Joe ever going to be glad to see you!',
  'Ta-da! Fresh air.',
  'I make a mean PB & J,',
  "Yeah, he's here, but...Joe can tell you about it.",
  'Marching fishes!',
  'It looks like a flip-flop with a bent nail in it.',
  'My light will guide us toward the others.',
  "Being a Digidestined means that sometimes you have to save the world, even if you're the one who caused the problem.",
  "Let's go get that evil, cute guy!",
  'This helmet makes my glasses look smaller!',
  'Perfecto!',
  "I didn't say I wanted to kiss him, duh, I just wanna marry him!",
  'Hero time, Wormmon!',
  "AH-HA! HA! HA! HA! HA-Oh, it's not that funny!",
  'Aaaaauuuuhhh!',
  "I've got you Cody!",
  'He...called me a punk.',
  'Uh, Davis... What are you doing?',
  '(thinking sarcastically) Thanks a lot, Davis. Great, no pressure.',
  'This Christmas party was a bad idea... I should forget the whole thing. But what am I going to do with all that eggnog?',
  'What could you digivolve into? A giant butterfly with scary looking wings?',
  "Eh, what the heck. I've got nine lives.",
  'What in the DigiWorld is she doing?',
  'Kari!',
  "She's losing it.",
  "The sky will be darkened by the wings of many bats.The fallen people will invoke the name of the undead Digimon king and when the clock strikes the hour of the beast, the undead king will reveal himself in his true form as the beast.Then angels will shoot arrows of hope and light at the loved ones of those they've been sent to protect, and a miracle will happen. Please always recycle."
]
